# Validating DC OPF Model, May 7, 2025

In [1]:
import pandas as pd
import pandapower as pp
from datetime import datetime
import matplotlib.pyplot as plt
import numpy as np
import copy
import copy
import pulp
import time
import pulp
import csv
import os
import random

#MY CODE BASE
import GridFlowSmooth as flow 

datelabel = str(datetime.now())[2:10]

# Testing on model's own merits

In [4]:
out, prob = flow.ACDC_TEP_OPF(gen_capacity = {1:150,2:0,3:0,4:0}, line_capacity = 100, 
                 susceptances = {(1,2):1500, (2,3):1500, (3,4):1500, (1,3):1500, (1,4):1500}, 
                 line_expansion_cost = 1000, buses = [1, 2, 3, 4], obj = 'cost', cut = False,
                 demands = {1: 30, 2: 20, 3: 20, 4: 20}, ac_lines = [(1, 2), (2,3), (3,4)], 
                 poss_ac_lines = [(1, 3), (1,4)], dc_lines = [], poss_dc_lines = [(3,1)], 
                 generation_cost = {1: 120}, printout = True,
                 max_new_ac = 0, max_new_dc = 0, label='base'+datelabel, save = True)

Status: Optimal
Objective Value: 10800.0

Generation at Each Bus:
Bus 1: 90.0 MW

AC Line Flows:
Line 1-2: 60.0 MW
Line 2-3: 40.0 MW
Line 3-4: 20.0 MW

Voltage phases:
Bus 1: -3.0615926535900013 rads
Bus 2: -3.1015926535900014 rads
Bus 3: -3.128259320256668 rads
Bus 4: -3.14159265359 rads

# Let's poke around our model

In [11]:
# binding generation
out, prob = flow.ACDC_TEP_OPF(gen_capacity = {1:90,2:0,3:0,4:0}, line_capacity = 100, 
                 susceptances = {(1,2):1000, (2,3):1000, (3,4):1000, (1,3):1000, (1,4):1500}, 
                 line_expansion_cost = 1000, buses = [1, 2, 3, 4], obj = 'cost', cut = False,
                 demands = {1: 30, 2: 20, 3: 20, 4: 20}, ac_lines = [(1, 2), (2,3), (3,4)], 
                 poss_ac_lines = [(1, 3), (1,4)], dc_lines = [], poss_dc_lines = [(3,1)], 
                 generation_cost = {1: 120}, printout = True,
                 max_new_ac = 0, max_new_dc = 0, label=datelabel, save = False)

Status: Optimal
Objective Value: 10800.0

Generation at Each Bus:
Bus 1: 90.0 MW

AC Line Flows:
Line 1-2: 60.0 MW
Line 2-3: 40.0 MW
Line 3-4: 20.0 MW

Voltage phases:
Bus 1: -3.0215926535900004 rads
Bus 2: -3.0815926535900005 rads
Bus 3: -3.1215926535900005 rads
Bus 4: -3.14159265359 rads

In [17]:
# failed generation
out, prob = flow.ACDC_TEP_OPF(gen_capacity = {1:89,2:0,3:0,4:0}, line_capacity = 100, 
                 susceptances = {(1,2):1000, (2,3):1000, (3,4):1000, (1,3):1000, (1,4):1500}, 
                 line_expansion_cost = 1000, buses = [1, 2, 3, 4], obj = 'cost', cut = False,
                 demands = {1: 30, 2: 20, 3: 20, 4: 20}, ac_lines = [(1, 2), (2,3), (3,4)], 
                 poss_ac_lines = [(1, 3), (1,4)], dc_lines = [], poss_dc_lines = [(3,1)], 
                 generation_cost = {1: 120}, printout = True,
                 max_new_ac = 0, max_new_dc = 0, label='genFail'+datelabel, save = True)

Did not converge
See returned problem object

In [19]:
os.listdir('GNN_Data')

['.ipynb_checkpoints',
 'edgesbase25-05-08.npy',
 'edgesgenFail.npy',
 'edgesgenFail25-05-08.npy',
 'nodesbase25-05-08.npy',
 'nodesgenFail.npy',
 'nodesgenFail25-05-08.npy']

In [21]:
np.load('GNN_Data/edgesgenFail25-05-08.npy')

array([[2.0e+00, 1.0e+00, 0.0e+00, 1.0e+03, 1.0e+02, 0.0e+00, 0.0e+00,
        0.0e+00, 0.0e+00],
       [3.0e+00, 2.0e+00, 0.0e+00, 1.0e+03, 1.0e+02, 0.0e+00, 0.0e+00,
        0.0e+00, 0.0e+00],
       [4.0e+00, 3.0e+00, 0.0e+00, 1.0e+03, 1.0e+02, 0.0e+00, 0.0e+00,
        0.0e+00, 0.0e+00],
       [3.0e+00, 1.0e+00, 0.0e+00, 1.0e+03, 1.0e+02, 0.0e+00, 0.0e+00,
        1.0e+00, 0.0e+00],
       [4.0e+00, 1.0e+00, 0.0e+00, 1.5e+03, 1.0e+02, 0.0e+00, 0.0e+00,
        1.0e+00, 0.0e+00]])

In [23]:
np.load('GNN_Data/nodesgenFail25-05-08.npy')

array([[ 1., 30., 89.,  0.,  0.],
       [ 2., 20.,  0.,  0.,  0.],
       [ 3., 20.,  0.,  0.,  0.],
       [ 4., 20.,  0.,  0.,  0.]])

In [25]:
# binding generation, line cap
out, prob = flow.ACDC_TEP_OPF(gen_capacity = {1:90,2:0,3:0,4:0}, line_capacity = 60, 
                 susceptances = {(1,2):1000, (2,3):1000, (3,4):1000, (1,3):1000, (1,4):1500}, 
                 line_expansion_cost = 1000, buses = [1, 2, 3, 4], obj = 'cost', cut = False,
                 demands = {1: 30, 2: 20, 3: 20, 4: 20}, ac_lines = [(1, 2), (2,3), (3,4)], 
                 poss_ac_lines = [(1, 3), (1,4)], dc_lines = [], poss_dc_lines = [(3,1)], 
                 generation_cost = {1: 120}, printout = True,
                 max_new_ac = 0, max_new_dc = 0, label=''+datelabel, save = False)

Status: Optimal
Objective Value: 10800.0

Generation at Each Bus:
Bus 1: 90.0 MW

AC Line Flows:
Line 1-2: 60.0 MW
Line 2-3: 40.0 MW
Line 3-4: 20.0 MW

Voltage phases:
Bus 1: -3.0215926535900004 rads
Bus 2: -3.0815926535900005 rads
Bus 3: -3.1215926535900005 rads
Bus 4: -3.14159265359 rads

In [27]:
os.listdir('GNN_Data')

['.ipynb_checkpoints',
 'edgesbase25-05-08.npy',
 'edgesgenFail25-05-08.npy',
 'nodesbase25-05-08.npy',
 'nodesgenFail25-05-08.npy']

In [29]:
# binding generation, faiiled line cap
out, prob = flow.ACDC_TEP_OPF(gen_capacity = {1:90,2:0,3:0,4:0}, line_capacity = 59, 
                 susceptances = {(1,2):1000, (2,3):1000, (3,4):1000, (1,3):1000, (1,4):1500}, 
                 line_expansion_cost = 1000, buses = [1, 2, 3, 4], obj = 'cost', cut = False,
                 demands = {1: 30, 2: 20, 3: 20, 4: 20}, ac_lines = [(1, 2), (2,3), (3,4)], 
                 poss_ac_lines = [(1, 3), (1,4)], dc_lines = [], poss_dc_lines = [(3,1)], 
                 generation_cost = {1: 120}, printout = True,
                 max_new_ac = 0, max_new_dc = 0, label='lineFail'+datelabel, save = True)

Did not converge
See returned problem object

In [35]:
# binding gen, linea cap, sus
sus = 120/(2*np.pi) # flow = B_{i,j}(phase_i - phase_j)
out, prob = flow.ACDC_TEP_OPF(gen_capacity = {1:90,2:0,3:0,4:0}, line_capacity = 60, 
                 susceptances = {(1,2):sus, (2,3):sus, (3,4):sus, (1,3):sus, (1,4):sus}, 
                 line_expansion_cost = 1000, buses = [1, 2, 3, 4], obj = 'cost', cut = False,
                 demands = {1: 30, 2: 20, 3: 20, 4: 20}, ac_lines = [(1, 2), (2,3), (3,4)], 
                 poss_ac_lines = [(1, 3), (1,4)], dc_lines = [], poss_dc_lines = [(3,1)], 
                 generation_cost = {1: 120}, printout = True,
                 max_new_ac = 0, max_new_dc = 0, label=' ', save = False)

Status: Optimal
Objective Value: 10800.0

Generation at Each Bus:
Bus 1: 90.0 MW

AC Line Flows:
Line 1-2: 60.0 MW
Line 2-3: 40.0 MW
Line 3-4: 20.0 MW

Voltage phases:
Bus 1: 3.14159265359 rads
Bus 2: 0.0 rads
Bus 3: -2.0943951024005107 rads
Bus 4: -3.14159265359 rads

In [6]:
# binding gen, linea cap, failed sus
sus = 120/(2*np.pi) - .01 # flow = B_{i,j}(phase_i - phase_j)
out, prob = flow.ACDC_TEP_OPF(gen_capacity = {1:90,2:0,3:0,4:0}, line_capacity = 60, 
                 susceptances = {(1,2):sus, (2,3):sus, (3,4):sus, (1,3):sus, (1,4):sus}, 
                 line_expansion_cost = 1000, buses = [1, 2, 3, 4], obj = 'cost', cut = False,
                 demands = {1: 30, 2: 20, 3: 20, 4: 20}, ac_lines = [(1, 2), (2,3), (3,4)], 
                 poss_ac_lines = [(1, 3), (1,4)], dc_lines = [], poss_dc_lines = [(3,1)], 
                 generation_cost = {1: 120}, printout = True,
                 max_new_ac = 0, max_new_dc = 0, label=datelabel, save = False)

Did not converge
See returned problem object

# Now let's run a general test

In [9]:
def get_partners(pairs, node):
    left = [pair[0] for pair in pairs if node==pair[1]]
    right = [pair[1] for pair in pairs if node==pair[0]]
    return left+right

def new_pairs(pairs, buses, n=3):
    out = []
    complete = [] 
    while len(out) < n and len(pairs + out) < (len(buses)-1)*len(buses)/2:
        node1 = random.choice(list(set(buses) - set(complete)))
        partners = get_partners(pairs+out, node1)
        if len(partners)<len(buses)-1:
            node2 = random.choice(list(set(buses) - set(partners + [node1])))
            out.append((node1, node2))
        else:
            complete.append(node1)
    return out

In [11]:
def suggest_rand(pairs, bus_list, n=3):
    out = []
    for i in range(n):
        a = random.choice(bus_list)
        b = random.choice(bus_list[:a]+bus)
        while (a,b) in pairs+out or (b,a) in pairs+out or a==b:
            a = random.choice(bus_list)
            b = random.choice(bus_list)
        out.append((a,b))
    return out

# Experiments
Loop:
* generate a random network of variable node count, demands, generators, and generation capacity.
* run our pulp solver
* save results

In [44]:
for trial in range(50):
    print(f"\n## # Running Simulated Grid Number {trial+1} # ##\n"*2)
    buses = np.arange(np.random.randint(6,12))
    n = len(buses)
    demands = {bus:np.random.randint(1,16) for bus in buses}
    line_capacity = np.random.randint(2,5)*50
    line_expansion_cost = 100
    obj = 'cost'
    cut = False
    ac_lines = new_pairs([], buses,
                            n = np.random.randint(len(buses)+3, 2*len(buses)))
    poss_ac_lines = new_pairs(ac_lines, buses, n = 1)
    poss_dc_lines = new_pairs([], buses, n = 1)
    dc_lines = []
    susceptances = {line : np.random.randint(10,20)*10 for line in ac_lines + poss_ac_lines}  
    
    gen_buses = np.random.choice(buses, np.random.randint(1, 4), replace = False)
    gen_capacity = {g : np.random.randint(5,9)*25* 
                           int(g in gen_buses) for g in buses}
    generation_cost = {g : np.random.randint(1,100) for g in buses if g in gen_buses}
    printout = True
    max_new_ac = 0 
    max_new_dc = 0
    label=datelabel
    save = False
    print('Total Generation:', np.sum(list(gen_capacity.values())))
    print('Total Demand:',np.sum(list(demands.values())))
    print('Gen Costs:', generation_cost)

    out, prob = flow.ACDC_TEP_OPF(gen_capacity = gen_capacity, line_capacity = line_capacity, 
             susceptances = susceptances, 
             line_expansion_cost = line_expansion_cost, buses = buses, obj = 'cost', cut = False,
             demands = demands, ac_lines = ac_lines, 
             poss_ac_lines = poss_ac_lines, dc_lines = dc_lines, poss_dc_lines = poss_dc_lines, 
             generation_cost = generation_cost, printout = True,
             max_new_ac = 0, max_new_dc = 0, label='test'+str(trial+1)+'_'+datelabel, save = True)
    if prob.status !=1:
        print('-->Our Model Failed')
        # keystr = 'gen_capacity line_capacity susceptances line_expansion_cost buses demands ac_lines poss_ac_lines poss_dc_lines generation_cost'
        # keys = keystr.split(' ')
        # values = [gen_capacity, line_capacity, susceptances, line_expansion_cost,
        #           buses, demands, ac_lines, poss_ac_lines, poss_dc_lines, generation_cost]
        # totD, totG= np.sum(list(demands.values())), np.sum(list(gen_capacity.values()))
        # file = open(f'DidNotConverge/totD{totD}-totG{totG}-{datelabel}.txt','w')
        # for i in range(len(keys)):
        #     file.write(f'{keys[i]}={values[i]}\n')
        # file.close()
    else:
        print('-->Our Model Converged')

## # Running Simulated Grid Number 1 # ##

## # Running Simulated Grid Number 1 # ##

Total Generation: 175
Total Demand: 63
Gen Costs: {6: 94}
Status: Optimal
Objective Value: 5922.0

Generation at Each Bus:
Bus 6: 63.0 MW

AC Line Flows:
Line 8-5: 5.367634128473583 MW
Line 7-1: 3.874972971366958 MW
Line 1-9: -2.4953670639324628 MW
Line 2-5: -12.0 MW
Line 5-0: 0.8962887443603336 MW
Line 10-5: 6.139331961568075 MW
Line 10-6: -11.872703181908435 MW
Line 4-9: -7.7504496478916565 MW
Line 8-6: -14.367634128473583 MW
Line 7-6: -11.605950651158764 MW
Line 7-9: 2.730977679791806 MW
Line 0-1: -4.370340035299421 MW
Line 6-9: 10.886064430481554 MW
Line 10-0: 4.733371220340359 MW
Line 3-5: 6.389322654318676 MW
Line 4-3: -3.2495503521083435 MW
Line 3-9: -1.3712253984490985 MW
Line 3-6: -11.267647607977835 MW

Voltage phases:
Bus 0: -3.0305555410336034 rads
Bus 1: -2.996937540762069 rads
Bus 2: -3.14159265359 rads
Bus 3: -2.9879646396199013 rads
Bus 4: -3.015044225887471 rads
Bus 5: -3.02159265359 rads
Bus 6: -2.875288163540123 rads
Bus 7: -2.9581878110483997 rads
Bus 8: -2.9858084260668427 rads
Bus 9: -2.97425238563541 rads
Bus 10: -2.9832218288301995 rads
-->Our Model Converged

## # Running Simulated Grid Number 2 # ##

## # Running Simulated Grid Number 2 # ##

Total Generation: 550
Total Demand: 81
Gen Costs: {2: 4, 7: 93, 8: 10}
Status: Optimal
Objective Value: 323.9999999999982

Generation at Each Bus:
Bus 2: 80.99999999999955 MW

AC Line Flows:
Line 8-3: -2.230563178284399 MW
Line 8-4: -3.1898463202060157 MW
Line 0-1: -3.0861284049188384 MW
Line 8-1: 8.386722980590392 MW
Line 4-7: 6.628155798968919 MW
Line 8-5: 5.752256966118821 MW
Line 8-7: 1.9657293417359938 MW
Line 5-3: -7.644452087572844 MW
Line 5-6: 7.396709053691666 MW
Line 3-7: 2.6226828250127596 MW
Line 6-0: -0.08612840491883844 MW
Line 2-8: 21.684299789954196 MW
Line 3-2: -25.01422175780101 MW
Line 7-1: 9.216567965717942 MW
Line 2-4: 20.30147845224434 MW
Line 1-6: 2.517162541389496 MW
Line 3-4: -1.4834763330691203 MW

Voltage phases:
Bus 0: -3.1410543510592572 rads
Bus 1: -3.1248115699807366 rads
Bus 2: -2.8742197135595315 rads
Bus 3: -3.040981191944872 rads
Bus 4: -3.0303849324229497 rads
Bus 5: -3.0887590174922024 rads
Bus 6: -3.14159265359 rads
Bus 7: -3.0672080201949994 rads
Bus 8: -3.0549222118091497 rads
-->Our Model Converged

## # Running Simulated Grid Number 3 # ##

## # Running Simulated Grid Number 3 # ##

Total Generation: 350
Total Demand: 41
Gen Costs: {0: 67, 5: 29}
Status: Optimal
Objective Value: 1189.0

Generation at Each Bus:
Bus 5: 41.0 MW

AC Line Flows:
Line 0-4: 4.124246922203814 MW
Line 4-1: -1.3885444861608125 MW
Line 0-3: -4.462236968479914 MW
Line 0-5: -12.28630053261162 MW
Line 2-1: -5.4872085916353734 MW
Line 3-5: -9.462236968479914 MW
Line 4-2: 3.5127914083646266 MW
Line 5-1: 12.251462498908722 MW
Line 0-1: 2.6242905788877238 MW

Voltage phases:
Bus 0: -3.0848244123722695 rads
Bus 1: -3.105011262979098 rads
Bus 2: -3.14159265359 rads
Bus 3: -3.0585759596165047 rads
Bus 4: -3.1123193918536276 rads
Bus 5: -3.0029157421548587 rads
-->Our Model Converged

## # Running Simulated Grid Number 4 # ##

## # Running Simulated Grid Number 4 # ##

Total Generation: 500
Total Demand: 92
Gen Costs: {3: 17, 4: 37, 7: 76}
Status: Optimal
Objective Value: 1564.0

Generation at Each Bus:
Bus 3: 92.0 MW

AC Line Flows:
Line 9-5: 26.534868433898055 MW
Line 4-5: 5.332146645926823 MW
Line 4-8: -2.98575975112118 MW
Line 1-9: -14.437998294814847 MW
Line 7-2: -5.175115207373302 MW
Line 0-6: -2.0 MW
Line 8-5: 7.132984920175204 MW
Line 5-2: 19.175115207373302 MW
Line 9-8: 20.68074637648158 MW
Line 6-7: 3.8248847926266762 MW
Line 6-5: -17.824884792626676 MW
Line 9-3: -82.0 MW
Line 1-8: 4.4379982948148475 MW
Line 9-4: 16.346386894805644 MW

Voltage phases:
Bus 0: -3.1166771389970664 rads
Bus 1: -2.916332837340545 rads
Bus 2: -3.0984666935285556 rads
Bus 3: -2.1953261172287206 rads
Bus 4: -2.962315238787999 rads
Bus 5: -2.991938275709815 rads
Bus 6: -3.1033438056637332 rads
Bus 7: -3.14159265359 rads
Bus 8: -2.94098838342285 rads
Bus 9: -2.8260953479979523 rads
-->Our Model Converged

## # Running Simulated Grid Number 5 # ##

## # Running Simulated Grid Number 5 # ##

Total Generation: 175
Total Demand: 74
Gen Costs: {4: 65}
Status: Optimal
Objective Value: 4810.0

Generation at Each Bus:
Bus 4: 74.0 MW

AC Line Flows:
Line 2-4: -17.50231574560259 MW
Line 4-0: 14.322038220913779 MW
Line 0-3: 3.3890999787420326 MW
Line 5-6: 1.4976842543974103 MW
Line 2-8: 12.0 MW
Line 3-4: -22.10858427565563 MW
Line 2-6: 4.50231574560259 MW
Line 4-7: 12.067061757828252 MW
Line 3-5: 10.296607315290672 MW
Line 3-1: 7.201076939106749 MW
Line 5-1: -4.201076939106749 MW
Line 0-7: -2.067061757828252 MW

Voltage phases:
Bus 0: -3.005919814641588 rads
Bus 1: -3.076184411707584 rads
Bus 2: -3.06159265359 rads
Bus 3: -3.0247481478568217 rads
Bus 4: -2.886569496133974 rads
Bus 5: -3.0982953429660407 rads
Bus 6: -3.106615811046026 rads
Bus 7: -2.987128344115876 rads
Bus 8: -3.14159265359 rads
-->Our Model Converged

## # Running Simulated Grid Number 6 # ##

## # Running Simulated Grid Number 6 # ##

Total Generation: 200
Total Demand: 105
Gen Costs: {4: 91}
Status: Optimal
Objective Value: 9554.99999999998

Generation at Each Bus:
Bus 4: 104.99999999999977 MW

AC Line Flows:
Line 6-3: 2.206447012752392 MW
Line 4-9: 29.92599715305431 MW
Line 7-5: 2.0506017044919247 MW
Line 0-8: -12.0 MW
Line 8-3: -14.33161459058715 MW
Line 7-1: 0.6917865518664144 MW
Line 5-9: -4.949398295508075 MW
Line 6-2: 15.0 MW
Line 1-9: -7.133374694094869 MW
Line 3-4: -32.86755583419307 MW
Line 8-9: -11.843224163451737 MW
Line 6-4: -32.20644701275239 MW
Line 8-1: -2.825161245961283 MW
Line 10-8: -2.0 MW
Line 7-3: -9.742388256358339 MW

Voltage phases:
Bus 0: -3.14159265359 rads
Bus 1: -3.021033348822695 rads
Bus 2: -2.9926889467064934 rads
Bus 3: -2.918997555913333 rads
Bus 4: -2.684229299954811 rads
Bus 5: -3.028483801444518 rads
Bus 6: -2.8989389467064934 rads
Bus 7: -3.0164214384769186 rads
Bus 8: -3.0492849612823076 rads
Bus 9: -2.983489271485354 rads
Bus 10: -3.061784961282308 rads
-->Our Model Converged

## # Running Simulated Grid Number 7 # ##

## # Running Simulated Grid Number 7 # ##

Total Generation: 350
Total Demand: 53
Gen Costs: {0: 92, 2: 17}
Status: Optimal
Objective Value: 901.0

Generation at Each Bus:
Bus 2: 53.0 MW

AC Line Flows:
Line 0-4: 2.4214720549606454 MW
Line 0-1: 1.4835728255479808 MW
Line 4-1: -2.4788359916603326 MW
Line 7-2: -11.10069230272606 MW
Line 5-3: 1.0174645502687838 MW
Line 6-5: -8.163755844695004 MW
Line 4-6: 5.836244155304996 MW
Line 1-3: 2.982535449731216 MW
Line 7-5: 3.16475619404207 MW
Line 2-0: 10.880044353307994 MW
Line 1-5: 1.7482444935784542 MW
Line 5-2: -12.293220234543867 MW
Line 1-2: -13.726043109422676 MW
Line 0-5: 1.9749994727994817 MW
Line 4-7: -3.9359361086839897 MW

Voltage phases:
Bus 0: -3.080670976903476 rads
Bus 1: -3.0889130481565203 rads
Bus 2: -3.0166707160016637 rads
Bus 3: -3.1046106031551055 rads
Bus 4: -3.1026843592213 rads
Bus 5: -3.0986255175652895 rads
Bus 6: -3.14159265359 rads
Bus 7: -3.0819689060176994 rads
-->Our Model Converged

## # Running Simulated Grid Number 8 # ##

## # Running Simulated Grid Number 8 # ##

Total Generation: 500
Total Demand: 69
Gen Costs: {0: 36, 3: 71, 7: 32}
Status: Optimal
Objective Value: 2208.0

Generation at Each Bus:
Bus 7: 69.0 MW

AC Line Flows:
Line 0-1: -2.2353457934789276 MW
Line 0-4: 0.8747439723611418 MW
Line 7-3: 21.359572044741924 MW
Line 2-5: 5.4205574037935635 MW
Line 2-0: -7.981258765094409 MW
Line 2-1: -7.170243337693979 MW
Line 7-0: 16.620656943976712 MW
Line 4-3: -1.1981127186129568 MW
Line 3-1: -1.6870385710826667 MW
Line 5-3: -7.5794425962064365 MW
Line 1-4: 2.9271433090259014 MW
Line 1-7: -26.019771011281478 MW
Line 1-6: 2.0 MW
Line 2-3: -5.269055301005174 MW

Voltage phases:
Bus 0: -3.0677003967235343 rads
Bus 1: -3.0545513038207175 rads
Bus 2: -3.109707021802979 rads
Bus 3: -3.0657982276279356 rads
Bus 4: -3.07284594950213 rads
Bus 5: -3.14159265359 rads
Bus 6: -3.0656624149318286 rads
Bus 7: -2.901493827283767 rads
-->Our Model Converged

## # Running Simulated Grid Number 9 # ##

## # Running Simulated Grid Number 9 # ##

Total Generation: 325
Total Demand: 52
Gen Costs: {5: 57, 6: 12}
Status: Optimal
Objective Value: 624.0

Generation at Each Bus:
Bus 6: 52.0 MW

AC Line Flows:
Line 0-6: -48.0 MW
Line 1-4: -3.0640864163573838 MW
Line 0-1: 25.446300064846007 MW
Line 4-0: -16.553699935153993 MW
Line 3-1: -7.785600578805213 MW
Line 1-5: 5.650767004194488 MW
Line 1-2: 1.0740188982036898 MW
Line 5-3: 1.2143994211947868 MW
Line 5-2: -5.563632417000298 MW
Line 2-4: -5.489613518796609 MW

Voltage phases:
Bus 0: -2.9520533258061117 rads
Bus 1: -3.0859812208842485 rads
Bus 2: -3.096721409866286 rads
Bus 3: -3.14159265359 rads
Bus 4: -3.062411325373807 rads
Bus 5: -3.129448659378052 rads
Bus 6: -2.6853866591394455 rads
-->Our Model Converged

## # Running Simulated Grid Number 10 # ##

## # Running Simulated Grid Number 10 # ##

Total Generation: 550
Total Demand: 60
Gen Costs: {0: 33, 3: 45, 5: 27}
Status: Optimal
Objective Value: 1619.9999999999939

Generation at Each Bus:
Bus 5: 59.99999999999977 MW

AC Line Flows:
Line 1-4: -2.069536418220167 MW
Line 1-0: -1.2170233300529958 MW
Line 1-2: -0.3713191558483686 MW
Line 5-3: 9.920656280337056 MW
Line 4-5: -11.02384773812986 MW
Line 5-0: 11.281404795889529 MW
Line 0-2: 1.064381465836533 MW
Line 2-3: -0.9206562803370559 MW
Line 5-2: 7.4319700897654 MW
Line 1-5: -8.342121095877928 MW
Line 4-2: 0.9543113199096922 MW

Voltage phases:
Bus 0: -3.1314507925062247 rads
Bus 1: -3.14159265359 rads
Bus 2: -3.1396383422434297 rads
Bus 3: -3.130431779440059 rads
Bus 4: -3.1300952290443327 rads
Bus 5: -3.0720749777910172 rads
-->Our Model Converged

## # Running Simulated Grid Number 11 # ##

## # Running Simulated Grid Number 11 # ##

Total Generation: 175
Total Demand: 63
Gen Costs: {5: 56}
Did not converge
See returned problem object
-->Our Model Failed

## # Running Simulated Grid Number 12 # ##

## # Running Simulated Grid Number 12 # ##

Total Generation: 450
Total Demand: 56
Gen Costs: {0: 80, 4: 11, 5: 45}
Status: Optimal
Objective Value: 615.9999999999953

Generation at Each Bus:
Bus 4: 55.999999999999574 MW

AC Line Flows:
Line 0-3: -1.1960264862703305 MW
Line 5-0: -0.2921621160749579 MW
Line 2-4: -23.569920312060397 MW
Line 5-6: -6.707837883925042 MW
Line 2-3: 7.792916996579539 MW
Line 1-6: -6.196435172924453 MW
Line 3-1: -1.8653180856487097 MW
Line 0-1: -3.1081204027570646 MW
Line 1-2: -10.77700331548086 MW
Line 4-6: 25.430079687939173 MW
Line 6-3: 6.537791404042117 MW
Line 0-6: -4.988015227047562 MW

Voltage phases:
Bus 0: -3.1398740529072064 rads
Bus 1: -3.122606717336333 rads
Bus 2: -3.062734476694773 rads
Bus 3: -3.133579176663678 rads
Bus 4: -2.8943779030371983 rads
Bus 5: -3.14159265359 rads
Bus 6: -3.0899939006367307 rads
-->Our Model Converged

## # Running Simulated Grid Number 13 # ##

## # Running Simulated Grid Number 13 # ##

Total Generation: 150
Total Demand: 42
Gen Costs: {0: 59}
Status: Optimal
Objective Value: 2478.0

Generation at Each Bus:
Bus 0: 42.0 MW

AC Line Flows:
Line 4-1: 0.7444321919284302 MW
Line 1-2: -6.25556780807157 MW
Line 2-0: -16.292094045697482 MW
Line 3-5: -1.524311306217566 MW
Line 2-5: 1.6812766414686848 MW
Line 3-4: 3.8795609023747946 MW
Line 3-2: -3.355249596157229 MW
Line 0-5: 17.707905954302518 MW
Line 5-4: 3.8648712895536352 MW

Voltage phases:
Bus 0: -2.9916473134346093 rads
Bus 1: -3.14159265359 rads
Bus 2: -3.0934729012202187 rads
Bus 3: -3.1132096635505553 rads
Bus 4: -3.137456919190398 rads
Bus 5: -3.1023217256490017 rads
-->Our Model Converged

## # Running Simulated Grid Number 14 # ##

## # Running Simulated Grid Number 14 # ##

Total Generation: 150
Total Demand: 86
Gen Costs: {8: 17}
Status: Optimal
Objective Value: 1462.0

Generation at Each Bus:
Bus 8: 86.0 MW

AC Line Flows:
Line 0-2: -2.5633344278425056 MW
Line 7-3: 7.037974683544348 MW
Line 5-6: 5.334081890956725 MW
Line 5-8: -34.419721713503606 MW
Line 8-7: 37.580278286496394 MW
Line 2-7: -6.5802782864963945 MW
Line 7-1: 8.746835443037952 MW
Line 5-2: 7.648974250389358 MW
Line 1-3: -1.253164556962048 MW
Line 5-0: 6.436665572157494 MW
Line 6-2: 1.3340818909567247 MW
Line 4-7: -3.215189873417728 MW
Line 3-4: -2.215189873417728 MW

Voltage phases:
Bus 0: -3.1358583590687426 rads
Bus 1: -3.14159265359 rads
Bus 2: -3.1198375188947267 rads
Bus 3: -3.1302002485267084 rads
Bus 4: -3.115432316037257 rads
Bus 5: -3.0773432175036746 rads
Bus 6: -3.1087201698034206 rads
Bus 7: -3.08328041730308 rads
Bus 8: -2.862219956794277 rads
-->Our Model Converged

## # Running Simulated Grid Number 15 # ##

## # Running Simulated Grid Number 15 # ##

Total Generation: 175
Total Demand: 45
Gen Costs: {3: 70}
Status: Optimal
Objective Value: 3150.0

Generation at Each Bus:
Bus 3: 45.0 MW

AC Line Flows:
Line 1-0: -3.004650501964477 MW
Line 0-4: 7.268245575388505 MW
Line 2-1: 1.6816623022317572 MW
Line 0-5: 3.6591711136542244 MW
Line 4-2: -6.386270506761093 MW
Line 5-1: -1.686312804196234 MW
Line 2-3: -14.06793280899285 MW
Line 5-4: 1.3454839178504585 MW
Line 0-3: -15.932067191007206 MW

Voltage phases:
Bus 0: -3.1012135115045085 rads
Bus 1: -3.119992577141785 rads
Bus 2: -3.1079807035544156 rads
Bus 3: -3.007495469204466 rads
Bus 4: -3.14159265359 rads
Bus 5: -3.1293609816095413 rads
-->Our Model Converged

## # Running Simulated Grid Number 16 # ##

## # Running Simulated Grid Number 16 # ##

Total Generation: 125
Total Demand: 73
Gen Costs: {5: 92}
Status: Optimal
Objective Value: 6715.999999999979

Generation at Each Bus:
Bus 5: 72.99999999999977 MW

AC Line Flows:
Line 5-2: 20.432657790047017 MW
Line 1-4: 4.784908297257532 MW
Line 6-3: 9.287329823972076 MW
Line 5-6: 20.287329823972076 MW
Line 0-6: -5.0 MW
Line 4-2: -3.215091702742468 MW
Line 5-1: 21.280012385980683 MW
Line 1-2: 0.7243883109932163 MW
Line 7-2: -6.229284222269939 MW
Line 3-2: -5.712670176027924 MW
Line 1-7: 8.77071577773006 MW

Voltage phases:
Bus 0: -3.0869173003878365 rads
Bus 1: -3.0741256091459217 rads
Bus 2: -3.0792998113673007 rads
Bus 3: -3.1129037535792294 rads
Bus 4: -3.104031286003781 rads
Bus 5: -2.9221255206746313 rads
Bus 6: -3.041462754933291 rads
Bus 7: -3.14159265359 rads
-->Our Model Converged

## # Running Simulated Grid Number 17 # ##

## # Running Simulated Grid Number 17 # ##

Total Generation: 275
Total Demand: 93
Gen Costs: {7: 16, 8: 90}
Status: Optimal
Objective Value: 1487.9999999999927

Generation at Each Bus:
Bus 7: 92.99999999999955 MW

AC Line Flows:
Line 2-8: 11.143700345294178 MW
Line 7-3: 5.0 MW
Line 2-6: 10.352685320646287 MW
Line 9-6: -4.351402554186109 MW
Line 0-7: -36.811990768632995 MW
Line 2-7: -38.18800923136655 MW
Line 2-0: -1.0811573635830314 MW
Line 5-1: -2.980686531820254 MW
Line 2-10: 12.772780929009116 MW
Line 8-1: 6.263411284327503 MW
Line 0-6: 12.730833405049964 MW
Line 1-10: -6.7172752474928075 MW
Line 10-6: -5.157120093150411 MW
Line 8-10: 2.374462456831907 MW
Line 10-5: 6.019313468179746 MW
Line 10-9: 1.567774763319278 MW
Line 0-4: 13.0 MW
Line 8-9: 3.080822682494613 MW
Line 8-6: -1.5749960783597317 MW

Voltage phases:
Bus 0: -2.980336666109981 rads
Bus 1: -3.1167535991581645 rads
Bus 2: -2.9901653694152808 rads
Bus 3: -2.755855413367058 rads
Bus 4: -3.088669999443314 rads
Bus 5: -3.14159265359 rads
Bus 6: -3.051063518360259 rads
Bus 7: -2.7173938749055195 rads
Bus 8: -3.0598134965733688 rads
Bus 9: -3.0906217233983124 rads
Bus 10: -3.081399518908203 rads
-->Our Model Converged

## # Running Simulated Grid Number 18 # ##

## # Running Simulated Grid Number 18 # ##

Total Generation: 500
Total Demand: 26
Gen Costs: {0: 11, 3: 94, 4: 84}
Status: Optimal
Objective Value: 285.99999999997857

Generation at Each Bus:
Bus 0: 25.999999999998053 MW

AC Line Flows:
Line 5-3: 0.06489796605767806 MW
Line 0-2: 8.995104947007462 MW
Line 6-1: 2.042218291906522 MW
Line 0-6: 7.356322931427826 MW
Line 3-6: -2.0246098788214795 MW
Line 6-5: 1.4161035117133813 MW
Line 6-2: 1.0050476143836704 MW
Line 3-1: 0.6064236010466857 MW
Line 6-4: -0.13165636539508796 MW
Line 5-2: -0.6487944543442967 MW
Line 3-4: -1.5169157561676787 MW
Line 0-4: 4.648572121562767 MW
Line 2-1: 1.3513581070469058 MW

Voltage phases:
Bus 0: -3.082610794281868 rads
Bus 1: -3.14159265359 rads
Bus 2: -3.1325835995430205 rads
Bus 3: -3.1365391235812776 rads
Bus 4: -3.1248705408415263 rads
Bus 5: -3.1359983071974633 rads
Bus 6: -3.1258832821137963 rads
-->Our Model Converged

## # Running Simulated Grid Number 19 # ##

## # Running Simulated Grid Number 19 # ##

Total Generation: 175
Total Demand: 47
Gen Costs: {3: 5}
Status: Optimal
Objective Value: 235.0

Generation at Each Bus:
Bus 3: 47.0 MW

AC Line Flows:
Line 3-0: 13.591384317597885 MW
Line 4-1: -0.9065646123880273 MW
Line 0-2: 0.5612635478000243 MW
Line 1-0: -1.4847809764596605 MW
Line 3-2: 12.343397943930881 MW
Line 1-2: -0.42178363592836693 MW
Line 6-4: -8.406026994757497 MW
Line 4-5: 2.017081314581788 MW
Line 4-2: -0.8889048505600385 MW
Line 3-4: 16.065217738471233 MW
Line 6-2: -6.593973005242503 MW
Line 0-5: 2.982918685418212 MW
Line 4-0: -1.5624211079199881 MW

Voltage phases:
Bus 0: -3.0760348089734317 rads
Bus 1: -3.0842835921759857 rads
Bus 2: -3.081647444451432 rads
Bus 3: -3.004501207301864 rads
Bus 4: -3.089054984872765 rads
Bus 5: -3.105863995827613 rads
Bus 6: -3.14159265359 rads
-->Our Model Converged

## # Running Simulated Grid Number 20 # ##

## # Running Simulated Grid Number 20 # ##

Total Generation: 550
Total Demand: 62
Gen Costs: {0: 15, 2: 14, 6: 75}
Status: Optimal
Objective Value: 1538.9999999999895

Generation at Each Bus:
Bus 2: 50.999999999999254 MW
Bus 6: 11.0 MW

AC Line Flows:
Line 5-4: 7.721048314593759 MW
Line 5-2: -11.437257143558318 MW
Line 2-1: 19.118135805652855 MW
Line 3-1: -2.4570060626398913 MW
Line 3-4: 1.7971275738281633 MW
Line 1-5: -0.7162088289645592 MW
Line 1-0: 3.377338571977873 MW
Line 0-3: -2.1044855396002227 MW
Line 2-3: 16.44460705078808 MW
Line 4-0: -0.4818241115780779 MW

Voltage phases:
Bus 0: -3.1367744124742196 rads
Bus 1: -3.1060713345471482 rads
Bus 2: -2.9865829857618182 rads
Bus 3: -3.123621377851719 rads
Bus 4: -3.14159265359 rads
Bus 5: -3.1009555571974015 rads
Bus 6: -3.14159265359 rads
-->Our Model Converged

## # Running Simulated Grid Number 21 # ##

## # Running Simulated Grid Number 21 # ##

Total Generation: 400
Total Demand: 75
Gen Costs: {0: 63, 6: 65}
Did not converge
See returned problem object
-->Our Model Failed

## # Running Simulated Grid Number 22 # ##

## # Running Simulated Grid Number 22 # ##

Total Generation: 200
Total Demand: 53
Gen Costs: {1: 86}
Status: Optimal
Objective Value: 4558.0

Generation at Each Bus:
Bus 1: 53.0 MW

AC Line Flows:
Line 4-7: -1.084627965554187 MW
Line 2-0: -0.33069765293328146 MW
Line 1-0: 16.870943818498404 MW
Line 6-3: 10.0 MW
Line 6-2: -9.910940919852974 MW
Line 0-5: 3.8504119731413766 MW
Line 4-6: 2.3805461356866666 MW
Line 2-1: -13.580243266919693 MW
Line 6-7: -3.605206226869595 MW
Line 6-5: -4.103306717591124 MW
Line 1-5: 16.54881291458264 MW
Line 0-7: 6.689834192423782 MW
Line 5-4: 2.2959181701324796 MW

Voltage phases:
Bus 0: -3.0149556707497416 rads
Bus 1: -2.92616122959975 rads
Bus 2: -3.016696184712548 rads
Bus 3: -3.141592653589999 rads
Bus 4: -3.0687659116153716 rads
Bus 5: -3.053459790481155 rads
Bus 6: -3.0827691241782347 rads
Bus 7: -3.062740200695626 rads
-->Our Model Converged

## # Running Simulated Grid Number 23 # ##

## # Running Simulated Grid Number 23 # ##

Total Generation: 475
Total Demand: 89
Gen Costs: {2: 99, 3: 39, 5: 30}
Status: Optimal
Objective Value: 2669.9999999999964

Generation at Each Bus:
Bus 5: 88.99999999999989 MW

AC Line Flows:
Line 6-7: -13.48915541028114 MW
Line 1-6: 0.510844589718859 MW
Line 3-0: 23.6088200889894 MW
Line 0-8: 2.415828043928114 MW
Line 1-2: -3.957683331683286 MW
Line 3-5: -28.6088200889894 MW
Line 7-5: -56.39117991101048 MW
Line 9-7: -10.0 MW
Line 4-7: -15.553161258035573 MW

we didn't converge on 11, 21, 36, 40, 44, 45 and 49

In [13]:
## #
## # node and edge matrix loading
## #
testname = 'test36_25-05-08.npy'
nodes = np.load('GNN_Data/nodes'+testname)
edges = np.load('GNN_Data/edges'+testname)

ac_lines = []
poss_ac_lines = []
dc_lines = []
poss_dc_lines = []
susceptances = {}
for row in edges:       # ## EDGES ## #
    if row[6]==0 and row[7]==0:
        ac_lines.append((row[0], row[1]))
        susceptances[(row[0],row[1])] = row[3]
        line_capacity = row[4]
    elif row[6]==0 and row[7]==1:
        poss_ac_lines.append((row[0], row[1]))
        susceptances[(row[0],row[1])] = row[3]
    elif row[6]==1 and row[7]==0:
        dc_lines.append((row[0], row[1]))
    else:
        poss_dc_lines.append((row[0], row[1]))
buses = list(nodes[:,0]) # ## NODES ## #
demands = {}
gen_capacity = {}
gen_buses = []
for row in nodes:       
    demands[row[0]] = row[1]
    gen_capacity[row[0]] = row[2]
    if row[2] >0:
        gen_buses.append(row[0])
        

generation_cost = {g : np.random.randint(1,100) for g in buses if g in gen_buses}

# ac_lines.append((5,7))
# susceptances[(5,7)] = 100
# solve test 11

# ac_lines.append((1,5))
# susceptances[(1,5)] = 100
# solve test 21

# ac_lines.append((2,4))
# susceptances[(2,4)] = 100
# solve test 36

In [15]:
nodes, line_capacity, susceptances, ac_lines

(array([[  0.,  10.,   0.,   0.,   0.],
        [  1.,   1.,   0.,   0.,   0.],
        [  2.,   5.,   0.,   0.,   0.],
        [  3.,   1.,   0.,   0.,   0.],
        [  4.,   7.,   0.,   0.,   0.],
        [  5.,   9.,   0.,   0.,   0.],
        [  6.,  12.,   0.,   0.,   0.],
        [  7.,   9., 175.,   0.,   0.],
        [  8.,  14.,   0.,   0.,   0.],
        [  9.,   6.,   0.,   0.,   0.]]),
 100.0,
 {(0.0, 3.0): 160.0,
  (5.0, 8.0): 180.0,
  (3.0, 1.0): 170.0,
  (9.0, 1.0): 100.0,
  (4.0, 7.0): 150.0,
  (3.0, 4.0): 190.0,
  (0.0, 4.0): 190.0,
  (7.0, 8.0): 190.0,
  (0.0, 7.0): 110.0,
  (3.0, 6.0): 100.0,
  (3.0, 9.0): 120.0,
  (0.0, 5.0): 170.0,
  (1.0, 4.0): 160.0,
  (5.0, 3.0): 120.0,
  (6.0, 1.0): 100.0,
  (3.0, 8.0): 170.0,
  (2.0, 3.0): 110.0},
 [(0.0, 3.0),
  (5.0, 8.0),
  (3.0, 1.0),
  (9.0, 1.0),
  (4.0, 7.0),
  (3.0, 4.0),
  (0.0, 4.0),
  (7.0, 8.0),
  (0.0, 7.0),
  (3.0, 6.0),
  (3.0, 9.0),
  (0.0, 5.0),
  (1.0, 4.0),
  (5.0, 3.0),
  (6.0, 1.0),
  (3.0, 8.0)])

In [21]:
flow.ACDC_TEP_OPF(gen_capacity = gen_capacity, line_capacity = line_capacity, 
             susceptances = susceptances, 
             line_expansion_cost = 100, buses = buses, obj = 'cost', cut = False,
             demands = demands, ac_lines = ac_lines, 
             poss_ac_lines = poss_ac_lines, dc_lines = dc_lines, poss_dc_lines = poss_dc_lines, 
             generation_cost = generation_cost, printout = True,
             max_new_ac = 1, max_new_dc = 0, label='retest36' +datelabel, save = False)

Status: Optimal
Objective Value: 6733.999999999802

Generation at Each Bus:
Bus 7.0: 73.99999999999783 MW

AC Line Flows:
Line 0.0-3.0: 4.321354631355177 MW
Line 5.0-8.0: -5.994488997239216 MW
Line 3.0-1.0: 1.687414424849976 MW
Line 9.0-1.0: -2.1858563342726995 MW
Line 4.0-7.0: -21.728758315822063 MW
Line 3.0-4.0: -6.429111695691972 MW
Line 0.0-4.0: -1.2975030709566795 MW
Line 7.0-8.0: 26.585632930790197 MW
Line 0.0-7.0: -16.685608753385566 MW
Line 3.0-6.0: 6.496298360250023 MW
Line 3.0-9.0: 3.8141436657273005 MW
Line 0.0-5.0: 3.661757192990251 MW
Line 1.0-4.0: -7.002143549172615 MW
Line 5.0-3.0: 0.656246190229453 MW
Line 6.0-1.0: -5.503701639749977 MW
Line 3.0-8.0: -6.591143933550995 MW
New AC Line 2.0-3.0: -5.0 MW

New AC Line Decisions:
Line 2.0-3.0: Added

New DC Line Decisions:

Voltage phases:
Bus 0.0: -3.0496212035415304 rads
Bus 1.0: -3.0865556371925003 rads
Bus 2.0: -3.1220842154420456 rads
Bus 3.0: -3.0766296699875 rads
Bus 4.0: -3.042792240010172 rads
Bus 5.0: -3.071160951735588 rads
Bus 6.0: -3.14159265359 rads
Bus 7.0: -2.897933851238025 rads
Bus 8.0: -3.0378582350842596 rads
Bus 9.0: -3.1084142005352278 rads

({'gen': {0.0: 0.0,
   1.0: 0.0,
   2.0: 0.0,
   3.0: 0.0,
   4.0: 0.0,
   5.0: 0.0,
   6.0: 0.0,
   7.0: 73.99999999999783,
   8.0: 0.0,
   9.0: 0.0},
  'curtail': {0.0: 0.0,
   1.0: 0.0,
   2.0: 0.0,
   3.0: 0.0,
   4.0: 0.0,
   5.0: 0.0,
   6.0: 0.0,
   7.0: 0.0,
   8.0: 0.0,
   9.0: 0.0},
  'ac_lines': [(0.0, 3.0),
   (5.0, 8.0),
   (3.0, 1.0),
   (9.0, 1.0),
   (4.0, 7.0),
   (3.0, 4.0),
   (0.0, 4.0),
   (7.0, 8.0),
   (0.0, 7.0),
   (3.0, 6.0),
   (3.0, 9.0),
   (0.0, 5.0),
   (1.0, 4.0),
   (5.0, 3.0),
   (6.0, 1.0),
   (3.0, 8.0)],
  'dc_lines': [],
  'phase': {0.0: -3.0496212035415304,
   1.0: -3.0865556371925003,
   2.0: -3.1220842154420456,
   3.0: -3.0766296699875,
   4.0: -3.042792240010172,
   5.0: -3.071160951735588,
   6.0: -3.14159265359,
   7.0: -2.897933851238025,
   8.0: -3.0378582350842596,
   9.0: -3.1084142005352278},
  'possible_ac': [(2.0, 3.0)],
  'possible_dc': [],
  'ac_flow': {(0.0, 3.0): 4.321354631355177,
   (5.0, 8.0): -5.994488997239216,
   (3.0, 1.0): 1.687414424849976,
   (9.0, 1.0): -2.1858563342726995,
   (4.0, 7.0): -21.728758315822063,
   (3.0, 4.0): -6.429111695691972,
   (0.0, 4.0): -1.2975030709566795,
   (7.0, 8.0): 26.585632930790197,
   (0.0, 7.0): -16.685608753385566,
   (3.0, 6.0): 6.496298360250023,
   (3.0, 9.0): 3.8141436657273005,
   (0.0, 5.0): 3.661757192990251,
   (1.0, 4.0): -7.002143549172615,
   (5.0, 3.0): 0.656246190229453,
   (6.0, 1.0): -5.503701639749977,
   (3.0, 8.0): -6.591143933550995},
  'poss_ac_flow': {(2.0, 3.0): -5.0},
  'dc_flow': {},
  'new_line': {(2.0, 3.0): 1.0},
  'new_dc_line': {}},
 Transmission_Expansion_DC_OPF:
 MINIMIZE
 91*gen_7.0 + 0
 SUBJECT TO
 Power_Balance_0.0: curtail_0.0 - flow_0.0_3.0 - flow_0.0_4.0 - flow_0.0_5.0
  - flow_0.0_7.0 + gen_0.0 = 10

 Power_Balance_1.0: curtail_1.0 - flow_1.0_4.0 + flow_3.0_1.0 + flow_6.0_1.0
  + flow_9.0_1.0 + gen_1.0 = 1

 Power_Balance_2.0: curtail_2.0 - flow_2.0_3.0 + gen_2.0 = 5

 Power_Balance_3.0: curtail_3.0 + flow_0.0_3.0 + flow_2.0_3.0 - flow_3.0_1.0
  - flow_3.0_4.0 - flow_3.0_6.0 - flow_3.0_8.0 - flow_3.0_9.0 + flow_5.0_3.0
  + gen_3.0 = 1

 Power_Balance_4.0: curtail_4.0 + flow_0.0_4.0 + flow_1.0_4.0 + flow_3.0_4.0
  - flow_4.0_7.0 + gen_4.0 = 7

 Power_Balance_5.0: curtail_5.0 + flow_0.0_5.0 - flow_5.0_3.0 - flow_5.0_8.0
  + gen_5.0 = 9

 Power_Balance_6.0: curtail_6.0 + flow_3.0_6.0 - flow_6.0_1.0 + gen_6.0 = 12

 Power_Balance_7.0: curtail_7.0 + flow_0.0_7.0 + flow_4.0_7.0 - flow_7.0_8.0
  + gen_7.0 = 9

 Power_Balance_8.0: curtail_8.0 + flow_3.0_8.0 + flow_5.0_8.0 + flow_7.0_8.0
  + gen_8.0 = 14

 Power_Balance_9.0: curtail_9.0 + flow_3.0_9.0 - flow_9.0_1.0 + gen_9.0 = 6

 Line_Capacity_Pos_2.0_3.0: flow_2.0_3.0 - 100 new_line_2.0_3.0 <= 0

 Line_Capacity_Neg_2.0_3.0: flow_2.0_3.0 + 100 new_line_2.0_3.0 >= 0

 Flow_phase_0.0_3.0: flow_0.0_3.0 - 160 phase_0.0 + 160 phase_3.0 = 0

 Flow_phase_5.0_8.0: flow_5.0_8.0 - 180 phase_5.0 + 180 phase_8.0 = 0

 Flow_phase_3.0_1.0: flow_3.0_1.0 + 170 phase_1.0 - 170 phase_3.0 = 0

 Flow_phase_9.0_1.0: flow_9.0_1.0 + 100 phase_1.0 - 100 phase_9.0 = 0

 Flow_phase_4.0_7.0: flow_4.0_7.0 - 150 phase_4.0 + 150 phase_7.0 = 0

 Flow_phase_3.0_4.0: flow_3.0_4.0 - 190 phase_3.0 + 190 phase_4.0 = 0

 Flow_phase_0.0_4.0: flow_0.0_4.0 - 190 phase_0.0 + 190 phase_4.0 = 0

 Flow_phase_7.0_8.0: flow_7.0_8.0 - 190 phase_7.0 + 190 phase_8.0 = 0

 Flow_phase_0.0_7.0: flow_0.0_7.0 - 110 phase_0.0 + 110 phase_7.0 = 0

 Flow_phase_3.0_6.0: flow_3.0_6.0 - 100 phase_3.0 + 100 phase_6.0 = 0

 Flow_phase_3.0_9.0: flow_3.0_9.0 - 120 phase_3.0 + 120 phase_9.0 = 0

 Flow_phase_0.0_5.0: flow_0.0_5.0 - 170 phase_0.0 + 170 phase_5.0 = 0

 Flow_phase_1.0_4.0: flow_1.0_4.0 - 160 phase_1.0 + 160 phase_4.0 = 0

 Flow_phase_5.0_3.0: flow_5.0_3.0 + 120 phase_3.0 - 120 phase_5.0 = 0

 Flow_phase_6.0_1.0: flow_6.0_1.0 + 100 phase_1.0 - 100 phase_6.0 = 0

 Flow_phase_3.0_8.0: flow_3.0_8.0 - 170 phase_3.0 + 170 phase_8.0 = 0

 Line_Flow_Pos_2.0_3.0: - flow_2.0_3.0 + 654321 new_line_2.0_3.0
  + 110 phase_2.0 - 110 phase_3.0 <= 654321

 Line_Flow_Neg_2.0_3.0: - flow_2.0_3.0 - 654321 new_line_2.0_3.0
  + 110 phase_2.0 - 110 phase_3.0 >= -654321

 max_AC_line: new_line_2.0_3.0 <= 1

 max_DC_line: __dummy <= 0

 VARIABLES
 __dummy = 0 Continuous
 curtail_0.0 = 0 Continuous
 curtail_1.0 = 0 Continuous
 curtail_2.0 = 0 Continuous
 curtail_3.0 = 0 Continuous
 curtail_4.0 = 0 Continuous
 curtail_5.0 = 0 Continuous
 curtail_6.0 = 0 Continuous
 curtail_7.0 = 0 Continuous
 curtail_8.0 = 0 Continuous
 curtail_9.0 = 0 Continuous
 -100 <= flow_0.0_3.0 <= 100 Continuous
 -100 <= flow_0.0_4.0 <= 100 Continuous
 -100 <= flow_0.0_5.0 <= 100 Continuous
 -100 <= flow_0.0_7.0 <= 100 Continuous
 -100 <= flow_1.0_4.0 <= 100 Continuous
 -100 <= flow_2.0_3.0 <= 100 Continuous
 -100 <= flow_3.0_1.0 <= 100 Continuous
 -100 <= flow_3.0_4.0 <= 100 Continuous
 -100 <= flow_3.0_6.0 <= 100 Continuous
 -100 <= flow_3.0_8.0 <= 100 Continuous
 -100 <= flow_3.0_9.0 <= 100 Continuous
 -100 <= flow_4.0_7.0 <= 100 Continuous
 -100 <= flow_5.0_3.0 <= 100 Continuous
 -100 <= flow_5.0_8.0 <= 100 Continuous
 -100 <= flow_6.0_1.0 <= 100 Continuous
 -100 <= flow_7.0_8.0 <= 100 Continuous
 -100 <= flow_9.0_1.0 <= 100 Continuous
 gen_0.0 = 0 Continuous
 gen_1.0 = 0 Continuous
 gen_2.0 = 0 Continuous
 gen_3.0 = 0 Continuous
 gen_4.0 = 0 Continuous
 gen_5.0 = 0 Continuous
 gen_6.0 = 0 Continuous
 gen_7.0 <= 175 Continuous
 gen_8.0 = 0 Continuous
 gen_9.0 = 0 Continuous
 0 <= new_line_2.0_3.0 <= 1 Integer
 -3.14159265359 <= phase_0.0 <= 3.14159265359 Continuous
 -3.14159265359 <= phase_1.0 <= 3.14159265359 Continuous
 -3.14159265359 <= phase_2.0 <= 3.14159265359 Continuous
 -3.14159265359 <= phase_3.0 <= 3.14159265359 Continuous
 -3.14159265359 <= phase_4.0 <= 3.14159265359 Continuous
 -3.14159265359 <= phase_5.0 <= 3.14159265359 Continuous
 -3.14159265359 <= phase_6.0 <= 3.14159265359 Continuous
 -3.14159265359 <= phase_7.0 <= 3.14159265359 Continuous
 -3.14159265359 <= phase_8.0 <= 3.14159265359 Continuous
 -3.14159265359 <= phase_9.0 <= 3.14159265359 Continuous)

# Let's try expansion

In [24]:
## #
## # node and edge matrix loading
## #
testname = 'test11_25-05-08.npy'
nodes = np.load('GNN_Data/nodes'+testname)
edges = np.load('GNN_Data/edges'+testname)

ac_lines = []
poss_ac_lines = []
dc_lines = []
poss_dc_lines = []
susceptances = {}
for row in edges:       # ## EDGES ## #
    if row[6]==0 and row[7]==0:
        ac_lines.append((row[0], row[1]))
        susceptances[(row[0],row[1])] = row[3]
        line_capacity = row[4]
    elif row[6]==0 and row[7]==1:
        poss_ac_lines.append((row[0], row[1]))
        susceptances[(row[0],row[1])] = row[3]
    elif row[6]==1 and row[7]==0:
        dc_lines.append((row[0], row[1]))
    else:
        poss_dc_lines.append((row[0], row[1]))
buses = list(nodes[:,0]) # ## NODES ## #
demands = {}
gen_capacity = {}
gen_buses = []
for row in nodes:       
    demands[row[0]] = row[1]
    gen_capacity[row[0]] = row[2]
    if row[2] >0:
        gen_buses.append(row[0])
        

generation_cost = {g : np.random.randint(1,100) for g in buses if g in gen_buses}

# ac_lines.append((5,7))
# susceptances[(5,7)] = 100
# solve test 11

# ac_lines.append((1,5))
# susceptances[(1,5)] = 100
# solve test 21

# ac_lines.append((2,4))
# susceptances[(2,4)] = 100
# solve test 36

In [32]:
susceptances[(7,5)] = 100
poss_ac_lines.append((7,5))
poss_ac_lines

[(6.0, 4.0), (7, 5)]

In [36]:
flow.ACDC_TEP_OPF(gen_capacity = gen_capacity, line_capacity = line_capacity, 
             susceptances = susceptances, 
             line_expansion_cost = 1, buses = buses, obj = 'curtail', cut = True,
             demands = demands, ac_lines = ac_lines, 
             poss_ac_lines = poss_ac_lines, dc_lines = dc_lines, poss_dc_lines = poss_dc_lines, 
             generation_cost = generation_cost, printout = True,
             max_new_ac = 1, max_new_dc = 0, label='retest11' +datelabel, save = False)

Status: Optimal
Objective Value: 0.0

Generation at Each Bus:
Bus 5.0: 63.0 MW

Curtailment:

AC Line Flows:
Line 1.0-4.0: -2.7287799779707456 MW
Line 4.0-5.0: -16.761521353992464 MW
Line 6.0-0.0: 3.4246034109848438 MW
Line 3.0-1.0: 6.91382420067751 MW
Line 2.0-1.0: -3.6426041786481846 MW
Line 4.0-3.0: -2.9000510343452532 MW
Line 0.0-4.0: -7.763975273761872 MW
Line 2.0-0.0: 2.8114213152532557 MW
Line 2.0-4.0: -5.168817136605071 MW
Line 6.0-5.0: -16.424603410984844 MW
Line 3.0-5.0: -12.813875235022692 MW
New AC Line 6.0-4.0: 0.0 MW
New AC Line 7-5: -12.0 MW

New AC Line Decisions:
Line 6.0-4.0: Not Added
Line 7-5: Added

New DC Line Decisions:

Voltage phases:
Bus 0.0: 2.972133351179532 rads
Bus 1.0: 3.0197782702652303 rads
Bus 2.0: 2.9937596689891715 rads
Bus 3.0: 3.0561668186898485 rads
Bus 4.0: 3.036833145127547 rads
Bus 5.0: 3.14159265359 rads
Bus 6.0: 2.9922780771265014 rads
Bus 7.0: 3.02159265359 rads

({'gen': {0.0: 0.0,
   1.0: 0.0,
   2.0: 0.0,
   3.0: 0.0,
   4.0: 0.0,
   5.0: 63.0,
   6.0: 0.0,
   7.0: 0.0},
  'curtail': {0.0: 0.0,
   1.0: 0.0,
   2.0: 0.0,
   3.0: 0.0,
   4.0: 0.0,
   5.0: 0.0,
   6.0: 0.0,
   7.0: 0.0},
  'ac_lines': [(1.0, 4.0),
   (4.0, 5.0),
   (6.0, 0.0),
   (3.0, 1.0),
   (2.0, 1.0),
   (4.0, 3.0),
   (0.0, 4.0),
   (2.0, 0.0),
   (2.0, 4.0),
   (6.0, 5.0),
   (3.0, 5.0)],
  'dc_lines': [],
  'phase': {0.0: 2.972133351179532,
   1.0: 3.0197782702652303,
   2.0: 2.9937596689891715,
   3.0: 3.0561668186898485,
   4.0: 3.036833145127547,
   5.0: 3.14159265359,
   6.0: 2.9922780771265014,
   7.0: 3.02159265359},
  'possible_ac': [(6.0, 4.0), (7, 5)],
  'possible_dc': [],
  'ac_flow': {(1.0, 4.0): -2.7287799779707456,
   (4.0, 5.0): -16.761521353992464,
   (6.0, 0.0): 3.4246034109848438,
   (3.0, 1.0): 6.91382420067751,
   (2.0, 1.0): -3.6426041786481846,
   (4.0, 3.0): -2.9000510343452532,
   (0.0, 4.0): -7.763975273761872,
   (2.0, 0.0): 2.8114213152532557,
   (2.0, 4.0): -5.168817136605071,
   (6.0, 5.0): -16.424603410984844,
   (3.0, 5.0): -12.813875235022692},
  'poss_ac_flow': {(6.0, 4.0): 0.0, (7, 5): -12.0},
  'dc_flow': {},
  'new_line': {(6.0, 4.0): 0.0, (7, 5): 1.0},
  'new_dc_line': {}},
 Transmission_Expansion_DC_OPF:
 MINIMIZE
 1*curtail_0.0 + 1*curtail_1.0 + 1*curtail_2.0 + 1*curtail_3.0 + 1*curtail_4.0 + 1*curtail_5.0 + 1*curtail_6.0 + 1*curtail_7.0 + 0
 SUBJECT TO
 Power_Balance_0.0: curtail_0.0 - flow_0.0_4.0 + flow_2.0_0.0 + flow_6.0_0.0
  + gen_0.0 = 14

 Power_Balance_1.0: curtail_1.0 - flow_1.0_4.0 + flow_2.0_1.0 + flow_3.0_1.0
  + gen_1.0 = 6

 Power_Balance_2.0: curtail_2.0 - flow_2.0_0.0 - flow_2.0_1.0 - flow_2.0_4.0
  + gen_2.0 = 6

 Power_Balance_3.0: curtail_3.0 - flow_3.0_1.0 - flow_3.0_5.0 + flow_4.0_3.0
  + gen_3.0 = 3

 Power_Balance_4.0: curtail_4.0 + flow_0.0_4.0 + flow_1.0_4.0 + flow_2.0_4.0
  - flow_4.0_3.0 - flow_4.0_5.0 + flow_6.0_4.0 + gen_4.0 = 4

 Power_Balance_5.0: curtail_5.0 + flow_3.0_5.0 + flow_4.0_5.0 + flow_6.0_5.0
  + flow_7_5 + gen_5.0 = 5

 Power_Balance_6.0: curtail_6.0 - flow_6.0_0.0 - flow_6.0_4.0 - flow_6.0_5.0
  + gen_6.0 = 13

 Power_Balance_7.0: curtail_7.0 - flow_7_5 + gen_7.0 = 12

 Line_Capacity_Pos_6.0_4.0: flow_6.0_4.0 - 100 new_line_6.0_4.0 <= 0

 Line_Capacity_Neg_6.0_4.0: flow_6.0_4.0 + 100 new_line_6.0_4.0 >= 0

 Line_Capacity_Pos_7_5: flow_7_5 - 100 new_line_7_5 <= 0

 Line_Capacity_Neg_7_5: flow_7_5 + 100 new_line_7_5 >= 0

 Flow_phase_1.0_4.0: flow_1.0_4.0 - 160 phase_1.0 + 160 phase_4.0 = 0

 Flow_phase_4.0_5.0: flow_4.0_5.0 - 160 phase_4.0 + 160 phase_5.0 = 0

 Flow_phase_6.0_0.0: flow_6.0_0.0 + 170 phase_0.0 - 170 phase_6.0 = 0

 Flow_phase_3.0_1.0: flow_3.0_1.0 + 190 phase_1.0 - 190 phase_3.0 = 0

 Flow_phase_2.0_1.0: flow_2.0_1.0 + 140 phase_1.0 - 140 phase_2.0 = 0

 Flow_phase_4.0_3.0: flow_4.0_3.0 + 150 phase_3.0 - 150 phase_4.0 = 0

 Flow_phase_0.0_4.0: flow_0.0_4.0 - 120 phase_0.0 + 120 phase_4.0 = 0

 Flow_phase_2.0_0.0: flow_2.0_0.0 + 130 phase_0.0 - 130 phase_2.0 = 0

 Flow_phase_2.0_4.0: flow_2.0_4.0 - 120 phase_2.0 + 120 phase_4.0 = 0

 Flow_phase_6.0_5.0: flow_6.0_5.0 + 110 phase_5.0 - 110 phase_6.0 = 0

 Flow_phase_3.0_5.0: flow_3.0_5.0 - 150 phase_3.0 + 150 phase_5.0 = 0

 Line_Flow_Pos_6.0_4.0: - flow_6.0_4.0 + 654321 new_line_6.0_4.0
  - 170 phase_4.0 + 170 phase_6.0 <= 654321

 Line_Flow_Neg_6.0_4.0: - flow_6.0_4.0 - 654321 new_line_6.0_4.0
  - 170 phase_4.0 + 170 phase_6.0 >= -654321

 Line_Flow_Pos_7_5: - flow_7_5 + 654321 new_line_7_5 - 100 phase_5.0
  + 100 phase_7.0 <= 654321

 Line_Flow_Neg_7_5: - flow_7_5 - 654321 new_line_7_5 - 100 phase_5.0
  + 100 phase_7.0 >= -654321

 max_AC_line: new_line_6.0_4.0 + new_line_7_5 <= 1

 max_DC_line: __dummy <= 0

 VARIABLES
 __dummy = 0 Continuous
 curtail_0.0 <= 14 Continuous
 curtail_1.0 <= 6 Continuous
 curtail_2.0 <= 6 Continuous
 curtail_3.0 <= 3 Continuous
 curtail_4.0 <= 4 Continuous
 curtail_5.0 <= 5 Continuous
 curtail_6.0 <= 13 Continuous
 curtail_7.0 <= 12 Continuous
 -100 <= flow_0.0_4.0 <= 100 Continuous
 -100 <= flow_1.0_4.0 <= 100 Continuous
 -100 <= flow_2.0_0.0 <= 100 Continuous
 -100 <= flow_2.0_1.0 <= 100 Continuous
 -100 <= flow_2.0_4.0 <= 100 Continuous
 -100 <= flow_3.0_1.0 <= 100 Continuous
 -100 <= flow_3.0_5.0 <= 100 Continuous
 -100 <= flow_4.0_3.0 <= 100 Continuous
 -100 <= flow_4.0_5.0 <= 100 Continuous
 -100 <= flow_6.0_0.0 <= 100 Continuous
 -100 <= flow_6.0_4.0 <= 100 Continuous
 -100 <= flow_6.0_5.0 <= 100 Continuous
 -100 <= flow_7_5 <= 100 Continuous
 gen_0.0 = 0 Continuous
 gen_1.0 = 0 Continuous
 gen_2.0 = 0 Continuous
 gen_3.0 = 0 Continuous
 gen_4.0 = 0 Continuous
 gen_5.0 <= 175 Continuous
 gen_6.0 = 0 Continuous
 gen_7.0 = 0 Continuous
 0 <= new_line_6.0_4.0 <= 1 Integer
 0 <= new_line_7_5 <= 1 Integer
 -3.14159265359 <= phase_0.0 <= 3.14159265359 Continuous
 -3.14159265359 <= phase_1.0 <= 3.14159265359 Continuous
 -3.14159265359 <= phase_2.0 <= 3.14159265359 Continuous
 -3.14159265359 <= phase_3.0 <= 3.14159265359 Continuous
 -3.14159265359 <= phase_4.0 <= 3.14159265359 Continuous
 -3.14159265359 <= phase_5.0 <= 3.14159265359 Continuous
 -3.14159265359 <= phase_6.0 <= 3.14159265359 Continuous
 -3.14159265359 <= phase_7.0 <= 3.14159265359 Continuous)

In [ ]:
ValResults = {'panda':[], 'our':[], 'nodes': [], 'lines':[], 
              'total demand':[], 'total capacity':[], 'gen error': [],
             'phase error': [], 'objective error': [], 'flow error': []}
for trial in range(200):
    # print(f"\n## # Running Simulated Grid Number {trial+1} # ##\n"*2)
    buses = np.arange(np.random.randint(6,12))
    n = len(buses)
    demands = {bus:np.random.randint(3,8)*20 for bus in buses}
    line_capacity = 1000
    line_expansion_cost = 1000
    obj = 'cost'
    cut = False
    ac_lines = new_pairs([], buses,
                            n = np.random.randint(len(buses)+3, 2*len(buses)+4))
    poss_ac_lines = new_pairs(ac_lines, buses, n = 1)
    poss_dc_lines = new_pairs([], buses, n = 1)
    dc_lines = []
    susceptances = {line : np.random.randint(10,20)*100 for line in ac_lines + poss_ac_lines}  
    
    gen_buses = np.random.choice(buses, np.random.randint(1, 5), replace = False)
    gen_capacity = {g : np.random.randint(5,9)*150* 
                           int(g in gen_buses) for g in buses}
    generation_cost = {g : np.random.randint(1,100) for g in buses if g in gen_buses}
    printout = True
    max_new_ac = 0 
    max_new_dc = 0
    label=datelabel
    save = False
    # print('Total Demand:',np.sum(list(demands.values())))
    # print('Gen Costs:', generation_cost)
    ValResults['nodes'].append( n)
    ValResults['lines'].append(len(ac_lines))
    ValResults['total demand'].append(np.sum(list(demands.values())))
    ValResults['total capacity'].append( np.sum(list(gen_capacity.values())))
    
    try:
        net = panda_DCOPF(gen_capacity = gen_capacity, line_capacity = line_capacity, 
                     susceptances = susceptances, 
                     line_expansion_cost = line_expansion_cost, buses = buses, obj = 'cost', cut = False,
                     demands = demands, ac_lines = ac_lines, 
                     dc_lines = dc_lines,
                     generation_cost = generation_cost, printout = False)
        # print('-->Panda Converged')
        ValResults['panda'].append(1)
        # print('Panda generators:')
        # print({net.gen['bus'][i]: net.res_gen['p_mw'][i] for i in net.gen.index })
        panda_gen = {net.gen['bus'][i]: net.res_gen['p_mw'][i] for i in net.gen.index }
    except Exception:
        # print('Panda Failed')
        ValResults['panda'].append(0)
        
    out, prob = flow.ACDC_TEP_OPF(gen_capacity = gen_capacity, line_capacity = line_capacity, 
             susceptances = susceptances, 
             line_expansion_cost = line_expansion_cost, buses = buses, obj = 'cost', cut = False,
             demands = demands, ac_lines = ac_lines, 
             poss_ac_lines = poss_ac_lines, dc_lines = dc_lines, poss_dc_lines = poss_dc_lines, 
             generation_cost = generation_cost, printout = False,
             max_new_ac = 0, max_new_dc = 0, label=datelabel, save = False)
    if prob.status !=1:
        # print('-->Our Model Failed')
        ValResults['our'].append(0)
        keystr = 'gen_capacity line_capacity susceptances line_expansion_cost buses demands ac_lines poss_ac_lines poss_dc_lines generation_cost'
        keys = keystr.split(' ')
        values = [gen_capacity, line_capacity, susceptances, line_expansion_cost,
                  buses, demands, ac_lines, poss_ac_lines, poss_dc_lines, generation_cost]
        totD, totG= np.sum(list(demands.values())), np.sum(list(gen_capacity.values()))
        file = open(f'DidNotConverge/totD{totD}-totG{totG}-{datelabel}.txt','w')
        for i in range(len(keys)):
            file.write(f'{keys[i]}={values[i]}\n')
        file.close()
        
        ValResults['gen error'].append(-1)
        ValResults['phase error'].append(-1)
        ValResults['flow error'].append(-1)
        ValResults['objective error'].append(-1)
    else:
        # print('-->Our Model Converged')
        ValResults['our'].append(1)
        flow_comp = pd.DataFrame({'PandaPower MW':list(net.res_line['p_from_mw'].values), 
                              'OurModel MW':list(out['ac_flow'].values())})
        flow_comp['Error MW'] = flow_comp['PandaPower MW']-flow_comp['OurModel MW']
        phase_comp = pd.DataFrame({'PandaPower rads':list(net.res_bus['va_degree'].values*np.pi/180), 
                                  'OurModel rads':list(out['phase'].values())})
        phase_comp['Error rads'] = phase_comp['PandaPower rads']-phase_comp['OurModel rads']
        sum_abs_flow_err = np.sum(np.abs(flow_comp['Error MW'].values))
        sum_abs_phase_err = np.sum(np.abs(phase_comp['Error rads'].values))
        # print("Our generators:")
        # print({key:out['gen'][key] for key in out['gen'] if gen_capacity[key] > 0})
        our_gen = {key:out['gen'][key] for key in out['gen'] if gen_capacity[key] > 0}
        sum_gen_err = np.sum([panda_gen[g] for g in our_gen]) - np.sum([our_gen[g] for g in our_gen]) 
        
        # print('Panda generators:')
        # print({net.gen['bus'][i]: net.res_gen['p_mw'][i] for i in net.gen.index })
        # print("Line Flows' Absolute Error :\n", sum_abs_flow_err)
        # print("Bus Phases:\n", sum_abs_phase_err)
        ValResults['phase error'].append( sum_abs_phase_err)
        ValResults['flow error'].append(sum_abs_flow_err)
        ValResults['gen error'].append(sum_gen_err)
        ValResults['objective error'].append(net.res_cost-prob.objective.value())

In [258]:
pd.DataFrame(ValResults).to_csv('Validate18april2025.csv')

In [222]:
prob.objective.value()

25200.0

In [226]:
net.res_cost

25200.00001785033

In [94]:
vis=[]
node0 = ac_lines[0][0]
for pair in ac_lines:
    if node0 == pair[0]:
        vis.append(pair[1])
    elif node0== pair[1]:
        vis.append(pair[0])

In [96]:
vis

[1, 5, 3, 2]

In [55]:
{net.gen['bus'][i]: net.res_gen['p_mw'][i] for i in net.gen.index }

{1: 419.99999958398973, 3: 4.160102549538972e-07}

In [51]:
net.gen.index

Index([0, 1], dtype='int64')

In [102]:
net.res_load

    p_mw  q_mvar
0  140.0     NaN
1   60.0     NaN
2   80.0     NaN
3   80.0     NaN
4   80.0     NaN
5   80.0     NaN
6  100.0     NaN
7    0.0     NaN
8   80.0     NaN

In [108]:
net.res_line

,p_from_mw,q_from_mvar,p_to_mw,q_to_mvar,pl_mw,ql_mvar,i_from_ka,i_to_ka,i_ka,vm_from_pu,va_from_degree,vm_to_pu,va_to_degree,loading_percent
0,32.841452,0.0,-32.841452,0.0,0.0,0.0,18.961021,18.961021,18.961021,1.0,-7.829529,1.0,-9.083980,1.896102
1,-51.139810,0.0,51.139810,0.0,0.0,0.0,29.525583,29.525583,29.525583,1.0,-10.493252,1.0,-7.829529,2.952558
2,66.317569,0.0,-66.317569,0.0,0.0,0.0,38.288467,38.288467,38.288467,1.0,-6.986149,1.0,-9.221277,3.828847
3,0.000000,0.0,-0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,1.0,-10.493252,1.0,-10.493252,0.000000
4,-146.317569,0.0,146.317569,0.0,0.0,0.0,84.476488,84.476488,84.476488,1.0,-6.986149,1.0,0.000000,8.447649
5,28.860190,0.0,-28.860190,0.0,0.0,0.0,16.662438,16.662438,16.662438,1.0,-9.221277,1.0,-10.493252,1.666244
6,0.000000,0.0,-0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,1.0,-6.832325,1.0,-6.832325,0.000000
7,0.000000,0.0,0.000000,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,62.542620,0.0,-62.542620,0.0,0.0,0.0,36.108999,36.108999,36.108999,1.0,-6.832325,1.0,-9.221277,3.610900
9,-47.158548,0.0,47.158548,0.0,0.0,0.0,27.227001,27.227001,27.227001,1.0,-9.083980,1.0,-6.832325,2.722700
10,0.000000,0.0,-0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,1.0,-7.829529,1.0,-7.829529,0.000000
11,-163.981262,0.0,163.981262,0.0,0.0,0.0,94.674626,94.674626,94.674626,1.0,-7.829529,1.0,0.000000,9.467463
12,138.906668,0.0,-138.906668,0.0,0.0,0.0,80.197802,80.197802,80.197802,1.0,0.000000,1.0,-4.421537,8.019780
13,58.906668,0.0,-58.906668,0.0,0.0,0.0,34.009781,34.009781,34.009781,1.0,-4.421537,1.0,-6.832325,3.400978
14,-190.794500,0.0,190.794500,0.0,0.0,0.0,110.155256,110.155256,110.155256,1.0,-6.832325,1.0,0.000000,11.015526

In [ ]:
net

In [70]:
out, prob = flow.ACDC_TEP_OPF(gen_capacity = gen_capacity, line_capacity = line_capacity, 
         susceptances = susceptances, 
         line_expansion_cost = line_expansion_cost, buses = buses, obj = 'cost', cut = False,
         demands = demands, ac_lines = ac_lines, 
         poss_ac_lines = poss_ac_lines, dc_lines = dc_lines, poss_dc_lines = poss_dc_lines, 
         generation_cost = generation_cost, printout = False,
         max_new_ac = 0, max_new_dc = 0, label=datelabel, save = False)

In [76]:
prob.status

0

In [84]:
net.gen

,name,bus,p_mw,vm_pu,sn_mva,min_q_mvar,max_q_mvar,scaling,slack,in_service,slack_weight,type,controllable,min_p_mw,max_p_mw
0,Gen Bus 1,1,0.0,1.02,NaN,-10.0,10.0,1.0,True,True,0.0,None,True,0.0,2000.0

In [37]:
buses = np.arange(np.random.randint(5,12))
n = len(buses)
demands = {bus:np.random.randint(3,8)*20 for bus in buses}
line_capacity = 1000
line_expansion_cost = 1000
obj = 'cost'
cut = False
ac_lines = suggest_rand([], buses,
                        n = np.random.randint(len(buses)+4, 2*len(buses)+4))
poss_ac_lines = suggest_rand(ac_lines, buses, n = 1)
poss_dc_lines = suggest_rand([], buses, n = 1)
dc_lines = []
susceptances = {line : np.random.randint(10,20)*100 for line in ac_lines + poss_ac_lines}  

gen_buses = np.random.choice(buses, np.random.randint(1, 3), replace = False)
gen_capacity = {g : np.random.randint(5,9)*250* 
                       int(g in gen_buses) for g in buses}
generation_cost = {g : np.random.randint(1,100) for g in buses if g in gen_buses}
printout = True
max_new_ac = 0 
max_new_dc = 0
label=datelabel
save = False
print('Total Demand:',np.sum(list(demands.values())))
print('Gen Costs:', generation_cost)

net = panda_DCOPF(gen_capacity = gen_capacity, line_capacity = line_capacity, 
                 susceptances = susceptances, 
                 line_expansion_cost = line_expansion_cost, buses = buses, obj = 'cost', cut = False,
                 demands = demands, ac_lines = ac_lines, 
                 dc_lines = dc_lines,
                 generation_cost = generation_cost, printout = False)

Total Demand: 520
Gen Costs: {1: 22, 4: 89}

In [112]:
out, net = panda_DCOPF(gen_capacity = gen_capacity, line_capacity = line_capacity, 
                 susceptances = susceptances, 
                 line_expansion_cost = line_expansion_cost, buses = buses, obj = 'cost', cut = False,
                 demands = demands, ac_lines = ac_lines, 
                 dc_lines = dc_lines,
                 generation_cost = generation_cost, printout = False)

In [114]:
net.res_gen

AttributeError: 'NoneType' object has no attribute 'res_gen'

In [49]:
 {'PandaPower MW':list(net.res_line['p_from_mw'].values), 
           'OurModel MW':list(out['ac_flow'].values())}

{'PandaPower MW': [59.9999913714589, 39.999994244336634, 19.999997121743547],
 'OurModel MW': [12.985536551073551,
  178.80886970514325,
  -18.18853429251078,
  -81.66747037414291,
  0.0,
  78.86330103734281,
  51.215261642261794,
  -43.96316298129386,
  15.08577663900337,
  -9.98730236773099,
  25.34699307478354,
  -284.13929496500293,
  58.653974724380305,
  8.641277092111409,
  -27.593608062881458,
  -237.05183532985356,
  -58.04322117769698,
  0.0,
  0.0]}

In [168]:
np.sum(list(gen_capacity.values()))

2500

In [172]:
(net.res_gen['p_mw']**2 + net.res_gen['p_mw']**2)**.5

0    1781.908379
1       0.000710
Name: p_mw, dtype: float64

In [202]:
net.res_line

,p_from_mw,q_from_mvar,p_to_mw,q_to_mvar,pl_mw,ql_mvar,i_from_ka,i_to_ka,i_ka,vm_from_pu,va_from_degree,vm_to_pu,va_to_degree,loading_percent
0,-116.265017,-8.421379,116.265017,19.150610,-1.421085e-14,10.729231,68.186020,68.186020,68.186020,0.987028,-21.258050,0.997714,-16.047401,6.818602
1,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,66.808625,12.530220,-66.808625,-10.078004,0.000000e+00,2.452215,39.409005,39.409005,39.409005,0.995826,-25.650528,0.989834,-27.694843,3.940900
3,61.674873,3.145255,-61.674873,-0.333409,0.000000e+00,2.811846,36.224229,36.224229,36.224229,0.984266,-26.222680,0.983003,-28.832351,3.622423
4,39.674723,-1.956759,-39.674723,2.806560,0.000000e+00,0.849801,23.199298,23.199298,23.199298,0.988567,-26.472065,0.989834,-27.694843,2.319930
5,-43.516652,7.271444,43.516652,-5.615809,-7.105427e-15,1.655636,25.734301,25.734301,25.734301,0.989834,-27.694843,0.984394,-25.561966,2.573430
6,142.926092,10.830179,-142.926092,1.574967,0.000000e+00,12.405146,83.842606,83.842606,83.842606,0.987028,-21.258050,0.984266,-26.222680,8.384261
7,-414.846383,-48.630698,414.846383,173.818473,0.000000e+00,125.187775,241.704285,241.704285,241.704285,0.997714,-16.047401,1.074395,0.000000,24.170429
8,13.407395,0.228644,-13.407395,-0.074013,0.000000e+00,0.154631,7.864623,7.864623,7.864623,0.984394,-25.561966,0.984266,-26.222680,0.786462
9,-4.658614,4.686831,4.658614,-4.646209,0.000000e+00,0.040623,3.859405,3.859405,3.859405,0.988567,-26.472065,0.984266,-26.222680,0.385941
10,-88.325127,0.333409,88.325127,4.712566,0.000000e+00,5.045975,51.876649,51.876649,51.876649,0.983003,-28.832351,0.984394,-25.561966,5.187665
11,-242.215523,-25.725272,242.215523,75.582361,0.000000e+00,49.857089,141.219105,141.219105,141.219105,0.995826,-25.650528,1.037349,-14.382763,14.121910
12,178.581366,29.480088,-178.581366,0.438713,-2.842171e-14,29.918802,104.738852,104.738852,104.738852,0.997714,-16.047401,0.984394,-25.561966,10.473885
13,159.609211,4.533200,-159.609211,10.005811,0.000000e+00,14.539010,93.399176,93.399176,93.399176,0.987028,-21.258050,0.988567,-26.472065,9.339918
14,332.215021,89.680428,-332.215021,-4.198027,0.000000e+00,85.482402,184.913387,184.913387,184.913387,1.074395,0.000000,1.037349,-14.382763,18.491339
15,-422.938093,-15.485130,422.938093,182.626506,-5.684342e-14,167.141376,247.558419,247.558419,247.558419,0.987028,-21.258050,1.074395,0.000000,24.755842
16,-25.406897,-12.735883,25.406897,13.195052,0.000000e+00,0.459169,16.598237,16.598237,16.598237,0.988567,-26.472065,0.995826,-25.650528,1.659824
17,116.667808,8.543131,-116.667808,0.235885,0.000000e+00,8.779016,68.426178,68.426178,68.426178,0.987028,-21.258050,0.984394,-25.561966,6.842618

In [204]:
out['ac_flow']

{(3, 4): 85.35791285973482,
 (1, 5): 302.79127436866753,
 (2, 0): -36.80720624275659,
 (6, 6): 0.0,
 (0, 1): -254.46854468067968,
 (7, 0): 38.42899967259527,
 (2, 4): 89.02931766249776,
 (3, 5): -87.17850489089983,
 (1, 2): 274.3111812780575,
 (6, 5): -125.61276947776764,
 (0, 3): 76.09033811051859,
 (2, 3): 42.08906985831641,
 (7, 1): -158.42899967259527,
 (6, 4): -24.387230522232358,
 (5, 4): 0.0}

In [156]:
line_capacity = 1000
line_expansion_cost = 1000
obj = 'cost'
cut = False
(ac_lines ,poss_ac_lines,poss_dc_lines ,susceptances  ,gen_buses ,gen_capacity ,
generation_cost, demands)

([(10, 7),
  (5, 5),
  (0, 4),
  (3, 9),
  (1, 4),
  (4, 2),
  (10, 3),
  (7, 6),
  (2, 3),
  (1, 3),
  (9, 2),
  (0, 8),
  (7, 2),
  (10, 1),
  (6, 8),
  (10, 6),
  (1, 0),
  (10, 2)],
 [(6, 3)],
 [(3, 6)],
 {(10, 7): 1300,
  (5, 5): 1300,
  (0, 4): 1900,
  (3, 9): 1400,
  (1, 4): 1900,
  (4, 2): 1200,
  (10, 3): 1700,
  (7, 6): 1400,
  (2, 3): 1200,
  (1, 3): 1100,
  (9, 2): 1600,
  (0, 8): 1200,
  (7, 2): 1100,
  (10, 1): 1800,
  (6, 8): 1200,
  (10, 6): 1100,
  (1, 0): 1800,
  (10, 2): 1600,
  (6, 3): 1200},
 array([8, 6]),
 {0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 1500, 7: 0, 8: 1000, 9: 0, 10: 0},
 {6: 56, 8: 59},
 {0: 150,
  1: 150,
  2: 150,
  3: 90,
  4: 150,
  5: 90,
  6: 90,
  7: 120,
  8: 90,
  9: 150,
  10: 120})

In [86]:
np.sum(list(demands.values()))

810

In [118]:
buses = np.arange(np.random.randint(4,10))
n = len(buses)
demands = {bus:np.random.randint(3,7)*30 for bus in buses}
np.sum(list(demands.values())), np.sum(list(gen_capacity.values()))

(990, 750)

In [120]:
datelabel

'25-04-16'

In [122]:
pulp.LpStatus

{0: 'Not Solved',
 1: 'Optimal',
 -1: 'Infeasible',
 -2: 'Unbounded',
 -3: 'Undefined'}